### PR TITLE
feat: improved documentation site and release process

### PR DESCRIPTION
**Pull request by maoo**
Dear ContextData team,

as discussed in the last FDC3 PMC, I'm sending a Pull Request to enable generation of documentation within the ContextData repository, as done for the [API Working Group](https://github.com/FDC3/API/pull/40)

The current result can be demoed on http://fdc3-context-data.finos.org ; please note that this deployment is based on my fork, nothing have been altered in the github.com/FDC3/ContextData repository.

Please note that:
- This PR is not ready to be merged (see below), though feedback and review is welcome
- The code points to pending Pull Requests, such as https://github.com/FDC3/FDC3/pull/1 , which defines the common HTML/CSS site layout and main navigation
- Before merging, some changes must be applied to fork-specific code pointers (see TODOs in `.travis.yml`)
- Before merging, I'll squash the Git commits to cleanup the git logs
- After merging, some changes must be applied to Travis CI settings, in order to use proper deployment keys

More info on the release and documentation publishing can be found on https://github.com/maoo/FDC3/blob/common-docs-layout/docs/README.md

Happy to adapt the PR or to ship it to any _pre-master_ branch.

Thanks,
  mao

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@semantic-release-bot). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If there are any questions, please don't hesitate to [get in touch with our Infrastructure Support team](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/77955298/Getting+in+Touch#GettinginTouch-InfrastructureSupport). /CC @finos-admin

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Comment by rikoe** [comment]
@maoo are we ready to update and merge this branch?

**Comment by maoo** [comment]
@rikoe - yes, the PR is ready. Please note that:
- Semantic Release is still disabled. To enable it, change https://github.com/maoo/ContextData/blob/docs-pages/package.json#L15 to `master`
- Website gets generated and updated everytime there's an update on master branch
- Common site styling is work in progress (check https://github.com/FDC3/FDC3/pull/1 )

After the merge, I will:
- Enable Travis CI builds for this GitHub repo
- Switch DNS entry for fdc3-context-data.finos.org
- Set GitHub Token, email and id on Travis Settings to authorize doc publishing

@finos-cla-bot[bot] check

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by rikoe** [comment]
@maoo we are out of date again! Can we merge after the current PRs are merged?

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by maoo** [comment]
Closing this PR and creating a new one to avoid cla bot issues.

**Pull request closed without merging**
